import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/authContext";
import { Toaster } from "@/components/ui/toaster";
import SideBar from "@/components/Common/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GreenScape-CMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <SideBar />
          {children}
          <Toaster />
        </AuthContextProvider>
      </body>
    </html>
  );
}
